louvre_p4:
    resource: "@LouvreP4Bundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

billet:
    path:    /billet
    defaults: { _controller: LouvreP4Bundle:Billet:index}

reservation:
    path:    /reservation
    defaults: { _controller: LouvreP4Bundle:Reservation:index}

