louvre_p4_homepage:
    path:     /
    defaults: { _controller: LouvreP4Bundle:Default:index }

client_home:
    path:    /p4
    defaults: { _controller: LouvreP4Bundle:Client:index }

client_view:
    path:    /p4/client/{id}
    defaults: { _controller: LouvreP4Bundle:Client:view }

client_request:
    path:    /p4/add
    defaults: { _controller: LouvreP4Bundle:Client:request }